---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argo-workflows
  namespace: flux-system
spec:
  releaseName: argo-workflows
  targetNamespace: kube-system
  storageNamespace: kube-system
  interval: 10m0s
  chart:
    spec:
      chart: argo-workflows
      version: v3.4.8
      sourceRef:
        kind: HelmRepository
        name: argo
  values: {}
  install: {}

  # https://github.com/argoproj/argo-helm/blob/main/charts/argo-workflows/values.yaml